//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErthQuakeIn2800.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkSlateGray")]
        public global::System.Drawing.Color DarkColor {
            get {
                return ((global::System.Drawing.Color)(this["DarkColor"]));
            }
            set {
                this["DarkColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MintCream")]
        public global::System.Drawing.Color FontDark {
            get {
                return ((global::System.Drawing.Color)(this["FontDark"]));
            }
            set {
                this["FontDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDarkMood {
            get {
                return ((bool)(this["IsDarkMood"]));
            }
            set {
                this["IsDarkMood"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isDefPath {
            get {
                return ((bool)(this["isDefPath"]));
            }
            set {
                this["isDefPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int cmbKhatarNesbi {
            get {
                return ((int)(this["cmbKhatarNesbi"]));
            }
            set {
                this["cmbKhatarNesbi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int cmbTipKhak {
            get {
                return ((int)(this["cmbTipKhak"]));
            }
            set {
                this["cmbTipKhak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int cmbDastebandiSsaze {
            get {
                return ((int)(this["cmbDastebandiSsaze"]));
            }
            set {
                this["cmbDastebandiSsaze"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int cmbRxCas1 {
            get {
                return ((int)(this["cmbRxCas1"]));
            }
            set {
                this["cmbRxCas1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int cmbRxCas2 {
            get {
                return ((int)(this["cmbRxCas2"]));
            }
            set {
                this["cmbRxCas2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int cmbRyCas1 {
            get {
                return ((int)(this["cmbRyCas1"]));
            }
            set {
                this["cmbRyCas1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int cmbRyCas2 {
            get {
                return ((int)(this["cmbRyCas2"]));
            }
            set {
                this["cmbRyCas2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int cmbMaharX {
            get {
                return ((int)(this["cmbMaharX"]));
            }
            set {
                this["cmbMaharX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int cmbMaharY {
            get {
                return ((int)(this["cmbMaharY"]));
            }
            set {
                this["cmbMaharY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string txtHeight {
            get {
                return ((string)(this["txtHeight"]));
            }
            set {
                this["txtHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rdoMotearef {
            get {
                return ((bool)(this["rdoMotearef"]));
            }
            set {
                this["rdoMotearef"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rdoNaMotearef {
            get {
                return ((bool)(this["rdoNaMotearef"]));
            }
            set {
                this["rdoNaMotearef"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int cmbSazeHaeMotearef {
            get {
                return ((int)(this["cmbSazeHaeMotearef"]));
            }
            set {
                this["cmbSazeHaeMotearef"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int cmbConcOrSteel {
            get {
                return ((int)(this["cmbConcOrSteel"]));
            }
            set {
                this["cmbConcOrSteel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string txtTDynamic {
            get {
                return ((string)(this["txtTDynamic"]));
            }
            set {
                this["txtTDynamic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkMianghabimaneAst {
            get {
                return ((bool)(this["chkMianghabimaneAst"]));
            }
            set {
                this["chkMianghabimaneAst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool preset_IsHavebeenSet {
            get {
                return ((bool)(this["preset_IsHavebeenSet"]));
            }
            set {
                this["preset_IsHavebeenSet"] = value;
            }
        }
    }
}
